### ISSUE TITLE
It can't parse monthes as numbers; feature request: support export with days of week and monthes as numbers

### ISSUE THREAD

**Issue by d00rsfan** [ua-cron/react#10]
Great project! but it require to prepare value: replace corresponding numbers in valid cron string by words.
Step to reproduce.
1. Use valid cron string containing only numbers  `'0 0 1 2,4 *'`,
2.  expected behaviour: "February and April" are checked.
3.  ab: monthes are unchecked.
example: [https://stackblitz.com/edit/react-p6d7gn?file=package.json,src%2FApp.js](https://stackblitz.com/edit/react-p6d7gn?file=package.json,src%2FApp.js)

PS days of weeks it parses correctly, so with `'0 0 * * 2,3'` Tuesday and Wednesday are checked.
It also will be nice to get values as only numbers.

**Comment by BzenkoSergey** [comment]
> Great project! but it require to prepare value: replace corresponding numbers in valid cron string by words. Step to reproduce.
> 
> 1. Use valid cron string containing only numbers  `'0 0 1 2,4 *'`,
> 2. expected behaviour: "February and April" are checked.
> 3. ab: monthes are unchecked.
>    example: https://stackblitz.com/edit/react-p6d7gn?file=package.json,src%2FApp.js
> 
> PS days of weeks it parses correctly, so with `'0 0 * * 2,3'` Tuesday and Wednesday are checked. It also will be nice to get values as only numbers.

working on it

**Comment by BzenkoSergey** [comment]
@d00rsfan fixed, try version 2.0.5

https://stackblitz.com/edit/react-h4i5gz?file=src/App.js
