### ISSUE TITLE
Generated Wrong Expression

### ISSUE THREAD

**Issue by MHasankhan** [ua-cron/react#14]
I am using this tool [freeformatter](https://www.freeformatter.com/cron-expression-generator-quartz.html) to generate cron expressions for my application. I found this library which is developed using similar approaches, but I encountered an issue. When I tried to generate the expression for "Every second starting at :09 seconds after the minute" using FreeFormatter, I got this expression: 9/1 * * ? * * *. However, when I chose the same options from our package interface, I got this expression: 9/1 * * * * * *. The same issue appears for other cron expressions.

**Comment by MHasankhan** [comment]
![image](https://github.com/ua-cron/react/assets/29171451/9b3bb63c-35c0-419f-95a8-6403b38cb1d9)
![image](https://github.com/ua-cron/react/assets/29171451/914c5915-6375-4450-8b48-6b0d3541a4a8)

**Comment by BzenkoSergey** [comment]
@MHasankhan Good catch! Will be fixed soon

**Comment by BzenkoSergey** [comment]
@MHasankhan issue fixed in version 2.0.7, try it
