### ISSUE TITLE
Unable to install package with yarn 3

### ISSUE THREAD

**Issue by aniravi24** [ua-cron/react#7]
When trying to install the latest version (2.0.3), this error comes up.

```
Error: @sbzen/re-cron@file:dist::locator=%40sbzen%2Fre-cron%40npm%3A2.0.3: ENOENT: no such file or directory, lstat 'node_modules/@sbzen/re-cron/dist'
```

**Comment by BzenkoSergey** [comment]
@aniravi24 should work fine with latest version 2.0.4, please check
```yarn add @sbzen/re-cron```

**Comment by aniravi24** [comment]
@BzenkoSergey it's working now, thank you! Appreciate the quick response.
