### ISSUE TITLE
404 not found for github.com/ua-cron/core; I need fork 'ua-cron/core'; please help me

### ISSUE THREAD

**Issue by qiushui123** [ua-cron/react#9]

**Comment by BzenkoSergey** [comment]
github.com/ua-cron/core is a private repo and  a repo of this lib [@sbzen/cron-core](https://www.npmjs.com/package/@sbzen/cron-core) which is used in @sbzen/re-cron

@qiushui123 
Please explain why you need fork of github.com/ua-cron/core?

**Comment by qiushui123** [comment]
> github.com/ua-cron/core is a private repo and a repo of this lib [@sbzen/cron-core](https://www.npmjs.com/package/@sbzen/cron-core) which is used in @sbzen/re-cron
> 
> @qiushui123 Please explain why you need fork of github.com/ua-cron/core?

i need add custom cron expression  as trading day

**Comment by BzenkoSergey** [comment]
@qiushui123 You have been granted access to that repo, please check.

**Comment by qiushui123** [comment]
> @qiushui123 You have been granted access to that repo, please check.

thank you very much
